# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-TT
version:      0.12
version_from: lib/Catalyst/View/TT.pm
installdirs:  site
requires:
    Catalyst:                      5.00
    Template:                      0
    Template::Timer:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
